### ISSUE TITLE
Encrypt DRIVES

### ISSUE THREAD

**Issue by Dontmindmes** [Virgula0/hidden-tear#1]
Hey can you make ir encrypt drives?

**Comment by Virgula0** [comment]
This is a project open source for educational purpose only not to hack someone encrypting entire drives. You can change the script by yourself. I think it's not easy encrypt drives, try to give to the program admin privileges and modifies the directory in "F:\\\\" to encrypt. Don't forget to change the "directory encrypt" engine. If you want to encrypt the "C:\\\\" drive you have also to consider that the "try{} check{}" while encrypting will ignore the encryption of windows files.

**Comment by Dontmindmes** [comment]
I tried everything but cant manage to encrypt drives :/

**Comment by Virgula0** [comment]
It depends by what kind of drive you want to encrypt

**Comment by Dontmindmes** [comment]
Im trying to encrypt E drive, is it possible to have it encrypt all drives

**Comment by Dontmindmes** [comment]
Also is it possible to have it in a console application not form?

**Comment by Virgula0** [comment]
closed #1

**Comment by CrysisUs** [comment]
the password is not sent to the server, what am I doing wrong ??? http://127.0.0.1/server/attacker_panel.php, configured the database - I enter the site, but writes here that No hacked machines found yet. I also write in the code, this address is http://127.0.0.1/server/attacker_panel.php. Help.
