### ISSUE TITLE
I keep getting an error

### ISSUE THREAD

**Issue by bobbyflyn** [Virgula0/hidden-tear#7]
Warning: session_start(): Cannot start session when headers already sent in /storage/ssd3/321/15907321/public_html/Server/attacker_panel.php on line 93

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /storage/ssd3/321/15907321/public_html/Server/connect_db.php:2 Stack trace: #0 /storage/ssd3/321/15907321/public_html/Server/attacker_panel.php(94): include() #1 {main} thrown in /storage/ssd3/321/15907321/public_html/Server/connect_db.php on line 2

**Comment by Virgula0** [comment]
The project runs with PHP5.6 and not above versions. Also, by what you sent seems to be a misconfiguration with your database. Check data you have inserted in `connct_db.php` to establish a correct communication with your local database. Make also sure you have `mysql` extensions enabled from your PHP.ini file.

**Comment by bobbyflyn** [comment]
is it possible you could update it to support php 7.4?

**Comment by Virgula0** [comment]
The project is old and no longer maintained. You can consider installing php5.6 on your machine and switch the version easily to run the project or replace the obsolete functions with newer ones by review the project by your own. It should not take a long time to do that.
